# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_wdg = QtWidgets.QWidget(self.centralwidget)
        self.output_wdg.setGeometry(QtCore.QRect(300, 0, 780, 720))
        self.output_wdg.setObjectName("output_wdg")
        self.input_wdg = QtWidgets.QWidget(self.centralwidget)
        self.input_wdg.setGeometry(QtCore.QRect(0, 0, 300, 720))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.input_wdg.setPalette(palette)
        self.input_wdg.setAutoFillBackground(True)
        self.input_wdg.setObjectName("input_wdg")
        self.tabWidget = QtWidgets.QTabWidget(self.input_wdg)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 300, 211))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.move_tb = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.move_tb.setFont(font)
        self.move_tb.setObjectName("move_tb")
        self.formLayoutWidget = QtWidgets.QWidget(self.move_tb)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 291, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.dx_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.dx_lbl.setObjectName("dx_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dx_lbl)
        self.dx_ent = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dx_ent.setObjectName("dx_ent")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dx_ent)
        self.dy_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.dy_lbl.setObjectName("dy_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dy_lbl)
        self.dy_ent = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dy_ent.setObjectName("dy_ent")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dy_ent)
        self.move_btn = QtWidgets.QPushButton(self.move_tb)
        self.move_btn.setGeometry(QtCore.QRect(0, 150, 291, 25))
        self.move_btn.setObjectName("move_btn")
        self.tabWidget.addTab(self.move_tb, "")
        self.scale_tb = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.scale_tb.setFont(font)
        self.scale_tb.setObjectName("scale_tb")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.scale_tb)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 291, 141))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.kx_lbl = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.kx_lbl.setObjectName("kx_lbl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kx_lbl)
        self.ky_lbl = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.ky_lbl.setObjectName("ky_lbl")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ky_lbl)
        self.xc_scl_lbl = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.xc_scl_lbl.setObjectName("xc_scl_lbl")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.xc_scl_lbl)
        self.yc_scl_lbl = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.yc_scl_lbl.setObjectName("yc_scl_lbl")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.yc_scl_lbl)
        self.kx_ent = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.kx_ent.setObjectName("kx_ent")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kx_ent)
        self.ky_ent = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ky_ent.setObjectName("ky_ent")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ky_ent)
        self.xc_scl_ent = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.xc_scl_ent.setObjectName("xc_scl_ent")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.xc_scl_ent)
        self.yc_scl_ent = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.yc_scl_ent.setObjectName("yc_scl_ent")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.yc_scl_ent)
        self.scale_btn = QtWidgets.QPushButton(self.scale_tb)
        self.scale_btn.setGeometry(QtCore.QRect(0, 150, 291, 25))
        self.scale_btn.setObjectName("scale_btn")
        self.tabWidget.addTab(self.scale_tb, "")
        self.rot = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.rot.setFont(font)
        self.rot.setObjectName("rot")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.rot)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 291, 141))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_rot = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_rot.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_rot.setContentsMargins(0, 0, 0, 0)
        self.formLayout_rot.setObjectName("formLayout_rot")
        self.angle_lbl = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.angle_lbl.setObjectName("angle_lbl")
        self.formLayout_rot.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.angle_lbl)
        self.angle_ent = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.angle_ent.setObjectName("angle_ent")
        self.formLayout_rot.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.angle_ent)
        self.xc_rot_lbl = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.xc_rot_lbl.setObjectName("xc_rot_lbl")
        self.formLayout_rot.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.xc_rot_lbl)
        self.xc_rot_ent = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.xc_rot_ent.setObjectName("xc_rot_ent")
        self.formLayout_rot.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.xc_rot_ent)
        self.yc_rot_lbl = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.yc_rot_lbl.setObjectName("yc_rot_lbl")
        self.formLayout_rot.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.yc_rot_lbl)
        self.yc_rot_ent = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.yc_rot_ent.setObjectName("yc_rot_ent")
        self.formLayout_rot.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.yc_rot_ent)
        self.rotate_btn = QtWidgets.QPushButton(self.rot)
        self.rotate_btn.setGeometry(QtCore.QRect(0, 150, 291, 25))
        self.rotate_btn.setObjectName("rotate_btn")
        self.tabWidget.addTab(self.rot, "")
        self.last_action_lbl = QtWidgets.QLabel(self.input_wdg)
        self.last_action_lbl.setGeometry(QtCore.QRect(10, 330, 281, 372))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.last_action_lbl.setFont(font)
        self.last_action_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.last_action_lbl.setObjectName("last_action_lbl")
        self.undo_btn = QtWidgets.QPushButton(self.input_wdg)
        self.undo_btn.setGeometry(QtCore.QRect(0, 240, 298, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.undo_btn.setFont(font)
        self.undo_btn.setObjectName("undo_btn")
        self.reset_btn = QtWidgets.QPushButton(self.input_wdg)
        self.reset_btn.setGeometry(QtCore.QRect(0, 266, 298, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.reset_btn.setFont(font)
        self.reset_btn.setObjectName("reset_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dx_lbl.setText(_translate("MainWindow", "dX     "))
        self.dy_lbl.setText(_translate("MainWindow", "dY"))
        self.move_btn.setText(_translate("MainWindow", "Move Picture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.move_tb), _translate("MainWindow", "Move"))
        self.kx_lbl.setText(_translate("MainWindow", "kX     "))
        self.ky_lbl.setText(_translate("MainWindow", "kY"))
        self.xc_scl_lbl.setText(_translate("MainWindow", "Xc"))
        self.yc_scl_lbl.setText(_translate("MainWindow", "Yc"))
        self.scale_btn.setText(_translate("MainWindow", "Scale Picture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scale_tb), _translate("MainWindow", "Scale"))
        self.angle_lbl.setText(_translate("MainWindow", "Angle"))
        self.xc_rot_lbl.setText(_translate("MainWindow", "Xc"))
        self.yc_rot_lbl.setText(_translate("MainWindow", "Yc"))
        self.rotate_btn.setText(_translate("MainWindow", "Rotate Picture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rot), _translate("MainWindow", "Rotate"))
        self.last_action_lbl.setText(_translate("MainWindow", "Current center position:"))
        self.undo_btn.setText(_translate("MainWindow", "Undo"))
        self.reset_btn.setText(_translate("MainWindow", "Reset picture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
